version: "3.8"

services:
  backend:
    build: ./backend
    env_file:
      - sensitive_info.env
    environment:
      - REQUEST_PORT=8082
      - NODE_ENV=development
      # - ${NODE_ENV-development}
      # - ${LETSENCRYPT_HOST?LETSENCRYPT_HOST is not defined in .env file}
      # - ${LETSENCRYPT_EMAIL?LETSENCRYPT_EMAIL is not defined in .env file}
    expose:
      - 8082
    ports:
      - 8082:8082

  pvtools:
    build: ./pvtools
    expose:
      - 80
    ports:
      - 8080:80
    depends_on:
      - backend